namespace DiagnosableExceptions;

/// <summary>
///     Represents the stage in the error documentation building process where examples of the error can be specified.
/// </summary>
public interface IErrorExamplesStage {

    /// <summary>
    ///     Adds one or more example exception instances illustrating how this error may appear at runtime.
    /// </summary>
    /// <typeparam name="TError">
    ///     The type of <see cref="DiagnosableException" /> produced by the example factories.
    /// </typeparam>
    /// <param name="exampleFactories">
    ///     Factories that create representative exception instances using realistic example values.
    /// </param>
    /// <remarks>
    ///     <para>
    ///         Examples are used to expose <b>realistic error messages</b> generated by the exception, helping readers
    ///         recognize the error in logs, monitoring tools, or user interfaces.
    ///     </para>
    ///     <para>
    ///         Instead of hard-coded message strings, factories are used so that the examples always reflect the actual
    ///         message format produced by the exception implementation. This prevents message drift and duplication.
    ///     </para>
    ///     <para>
    ///         Each factory should construct an exception using plausible domain values (e.g., dates, identifiers, amounts,
    ///         units) that illustrate a typical failure case. These examples are descriptive, not executable scenarios or
    ///         tests.
    ///     </para>
    ///     <para>
    ///         <b>Writing guidance:</b>
    ///     </para>
    ///     <list type="bullet">
    ///         <item>Use realistic but simple values that clearly demonstrate the violation.</item>
    ///         <item>Avoid edge cases meant for testing rather than illustration.</item>
    ///         <item>Ensure the example focuses on the rule violation, not on technical side effects.</item>
    ///     </list>
    /// </remarks>
    ErrorDocumentation WithExamples<TError>(params Func<TError>[] exampleFactories)
        where TError : Error;

}